apiVersion: v1
kind: ConfigMap
metadata:
  name: environments
data:
  ollama: |
    [
      {"name": "LLM_API_BASE", "value": "http://host.docker.internal:11434/v1"},
      {"name": "LLM_API_KEY", "value": "dummy"},
      {"name": "LLM_MODEL", "value": "llama3.2:3b-instruct-fp16"}
    ]
  openai: |
    [
      {
        "name": "OPENAI_API_KEY",
        "valueFrom": {"secretKeyRef": {"name": "openai-secret", "key": "apikey"}}
      },
      {
        "name": "LLM_API_KEY",
        "valueFrom": {"secretKeyRef": {"name": "openai-secret", "key": "apikey"}}
      },
      {"name": "LLM_API_BASE", "value": "https://api.openai.com/v1"},
      {"name": "LLM_MODEL", "value": "gpt-4o-mini-2024-07-18"}
    ]
  mcp-weather: |
    [
      {"name": "MCP_URL", "value": "http://weather-tool:8000/mcp"}
    ]
  mcp-slack: |
    [
      {"name": "MCP_URL", "value": "http://slack-tool:8000/mcp"}
    ]
  slack-researcher-config: |
    [
      {"name": "EXTRA_HEADERS", "value": "{}"},
      {"name": "MODEL_TEMPERATURE", "value": "0"},
      {"name": "MAX_PLAN_STEPS", "value": "6"},
      {"name": "SERVICE_PORT", "value": "8000"},
      {"name": "LOG_LEVEL", "value": "INFO"}
    ]
  slack-researcher-auth-config: |
    [
      {
        "name": "CLIENT_SECRET",
        "valueFrom": {"secretKeyRef": {"name": "slack-agent-client-secret", "key": "client-secret"}}
      },
      {
        "name": "JWKS_URL",
        "value": "http://keycloak.keycloak.svc.cluster.local:8080/realms/master/protocol/openid-connect/certs"
      },
      {"name": "AUDIENCE", "value": "spiffe://localtest.me/sa/slack-tool"},
      {"name": "ISSUER", "value": "http://keycloak.localtest.me:8080/realms/master"}
    ]
  mcp-slack-config: |
    [
      {
        "name": "SLACK_BOT_TOKEN",
        "valueFrom": {"secretKeyRef": {"name": "slack-secret", "key": "bot-token"}}
      }
    ]
  mcp-slack-auth-config: |
    [
      {
        "name": "CLIENT_SECRET",
        "valueFrom": {"secretKeyRef": {"name": "slack-tool-client-secret", "key": "client-secret"}}
      }, 
      {
        "name": "ISSUER",
        "value": "http://keycloak.localtest.me:8080/realms/master"
      },
      {
        "name": "INTROSPECTION_ENDPOINT",
        "value": "http://keycloak.keycloak.svc.cluster.local:8080/realms/master/protocol/openid-connect/token/introspect"
      },
      {
        "name": "AUDIENCE",
        "value": "spiffe://localtest.me/sa/slack-tool"
      },
      {
        "name": "ADMIN_SLACK_BOT_TOKEN",
        "valueFrom": {"secretKeyRef": {"name": "slack-secret", "key": "admin-bot-token"}}
      },
      {
        "name": "ADMIN_SCOPE_NAME",
        "value": "slack-full-access"
      }
    ]
  KEYCLOAK_URL: "http://keycloak.keycloak:8080"
  KEYCLOAK_REALM: "master"
  KEYCLOAK_ADMIN_USERNAME: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
